// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
    UserPost: typeof import('./src/components/UserPost.vue')['default']
    UserPostHeader: typeof import('./src/components/UserPostHeader.vue')['default']
  }
}
