// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountIcon: typeof import('./src/components/icons/AccountIcon.vue')['default']
    BackIcon: typeof import('./src/components/icons/BackIcon.vue')['default']
    FeedLayout: typeof import('./src/components/FeedLayout.vue')['default']
    FriendLayout: typeof import('./src/components/FriendLayout.vue')['default']
    MyMemories: typeof import('./src/components/MyMemories.vue')['default']
    MyPost: typeof import('./src/components/MyPost.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostPhotos: typeof import('./src/components/PostPhotos.vue')['default']
    RealmojiWithIcon: typeof import('./src/components/RealmojiWithIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareIcon: typeof import('./src/components/icons/ShareIcon.vue')['default']
    SkeletonMyPost: typeof import('./src/components/skeleton/SkeletonMyPost.vue')['default']
    SkeletonUserIcon: typeof import('./src/components/skeleton/SkeletonUserIcon.vue')['default']
    SkeletonUserPost: typeof import('./src/components/skeleton/SkeletonUserPost.vue')['default']
    SkeletonUserPostHeader: typeof import('./src/components/skeleton/SkeletonUserPostHeader.vue')['default']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
    UserPost: typeof import('./src/components/UserPost.vue')['default']
    UserPostHeader: typeof import('./src/components/UserPostHeader.vue')['default']
    UserPostRealMojis: typeof import('./src/components/UserPostRealMojis.vue')['default']
  }
}
