// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RealmojiWithIcon: typeof import('./src/components/RealmojiWithIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonUserIcon: typeof import('./src/components/skeleton/SkeletonUserIcon.vue')['default']
    SkeletonUserPost: typeof import('./src/components/skeleton/SkeletonUserPost.vue')['default']
    SkeletonUserPostHeader: typeof import('./src/components/skeleton/SkeletonUserPostHeader.vue')['default']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
    UserPost: typeof import('./src/components/UserPost.vue')['default']
    UserPostHeader: typeof import('./src/components/UserPostHeader.vue')['default']
  }
}
